### PR TITLE
Uses parentheses with print() according to Python3 spec

### PR DESCRIPTION
**Pull request by rosatolen**
It looks like I can get psychic to run with the latest Python 3.5.2 with these small changes. :D

### CODE REVIEW

**Comment by dudadornelles** [comment]
Awesome! thanks for the PR. Are you actually using it?

**Comment by rosatolen** [comment]
Yes. :) When will pip get the latest version?

**Comment by dudadornelles** [comment]
Oh yeah, will do it

**Comment by rosatolen** [comment]
Thanks a lot

**Comment by dudadornelles** [comment]
Version 1.2.1 is out there.

Cheers!

**Pull request merged**
